notifications:
  webhooks:
    urls:
      - https://hooks.glipdemo.com/webhook/a68a48ebasdadc5ed2e
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
